name: CI/CD

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build pjsip universal library
      run: ./build.sh
    - name: Upload libraries
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libs
        path: build/
    - name: Check Tag
      id: check-tag
      run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+.*$ ]]; then
              echo ::set-output name=match::true
          else
            echo ::set-output name=match::true 
          fi
    - name: Check Tag Output
      if: steps.check-tag.outputs.match == 'true'
      run: |
        echo "Tag is a match"
    - name: Deploy Release
      if: steps.check-tag.outputs.match == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "libs"
        tag: ${{ github.ref }}
        
        
