name: Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build pjsip universal library
      run: ./build.sh
    - name: Upload libraries
      uses: actions/upload-artifact@v1.0.0
      with:
        name: libs
        path: build/
